{
    'name': 'Advanced School CRM',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Enterprise school management suite: admissions CRM, academics, attendance, fees, exams, assets, public website and parent/student portal',
    'author': 'Kamal Pant',
    'depends': ['base', 'mail', 'portal', 'website', 'utm', 'payment'],
    'application': True,
    'data': [
        'security/edu_security.xml',
        'security/edu_security_rules.xml',
        'security/ir.model.access.csv',

        'data/edu_sequence_data.xml',
        'data/edu_crm_stage_data.xml',
        'data/edu_lead_lost_reason_data.xml',
        'data/edu_utm_source_data.xml',
        'data/edu_portal_entry_data.xml',
        'data/edu_website_config_data.xml',
        'data/edu_mail_templates.xml',
        'data/edu_cron_data.xml',

        'views/edu_academic_year_views.xml',
        'views/edu_subject_views.xml',
        'views/edu_program_views.xml',
        'views/edu_guardian_views.xml',
        'views/edu_student_views.xml',
        'views/edu_class_views.xml',
        'views/edu_teacher_views.xml',
        'views/edu_attendance_views.xml',
        'views/edu_exam_views.xml',
        'views/edu_fee_views.xml',
        'views/edu_timetable_views.xml',
        'views/edu_announcement_views.xml',
        'views/edu_leave_views.xml',
        'views/edu_crm_stage_views.xml',
        'views/edu_lead_views.xml',
        'views/edu_applicant_views.xml',
        'wizard/edu_attendance_wizard_views.xml',
        'wizard/edu_fee_payment_wizard_views.xml',
        'wizard/edu_lead_convert_wizard_views.xml',
        'wizard/edu_applicant_enroll_wizard_views.xml',
        'wizard/edu_demo_data_wizard_views.xml',
        'wizard/edu_asset_checkout_wizard_views.xml',
        'views/edu_reports_analysis_views.xml',
        'views/edu_asset_views.xml',
        'views/edu_dashboard_views.xml',
        'views/menu_views.xml',

        'website_templates/page_home.xml',
        'website_templates/page_admissions.xml',
        'website_templates/page_features.xml',
        'website_templates/page_student_management.xml',
        'website_templates/page_attendance_management.xml',
        'website_templates/page_academic_management.xml',
        'website_templates/page_teacher_management.xml',
        'website_templates/page_examination_results.xml',
        'website_templates/page_fees_finance.xml',
        'website_templates/page_contact_us.xml',
        'website_templates/website_nav_data.xml',

        'portal_templates/portal_templates.xml',

        'reports/edu_reports.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'edu_crm/static/src/css/edu_crm_website.css',
        ],
        'web.assets_backend': [
            'edu_crm/static/src/css/edu_crm_backend.css',
            'edu_crm/static/src/css/edu_crm_dashboard.css',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
