from . import edu_academic_year
from . import edu_class
from . import edu_subject
from . import edu_program
from . import edu_teacher
from . import edu_guardian
from . import edu_student
from . import edu_attendance
from . import edu_exam
from . import edu_fee
from . import edu_timetable
from . import edu_announcement
from . import edu_leave_request
from . import edu_lead_lost_reason
from . import edu_crm_stage
from . import edu_lead
from . import edu_applicant
from . import edu_asset_category
from . import edu_asset
from . import edu_dashboard
from . import edu_payment_transaction
from . import res_users
